### ISSUE TITLE
Improve locale support

### ISSUE THREAD

**Issue by jamierocks** [Histacom/HistacomRewrite#1]

**Comment by ghost** [comment]
Couldn't you do it? I am planning to do so though, expect the commit tomorrow.

**Comment by jamierocks** [comment]
Ok, I'll do it :P

**Comment by ghost** [comment]
Ok thanks. IRC?

**Comment by jamierocks** [comment]
Ok.

**Comment by jamierocks** [comment]
https://github.com/Histacom/HistacomRewrite/commit/e237055ffbdc04c1363002f1fe219e93e9f462a5
